language: python

os:
  - linux

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - pytest
after_success:
  - coveralls

#run scripts to deploy to pypi:
#python3 setup.py sdist
#twine check dist/*
#twine upload