language: python

os:
  - linux
  - osx
  - windows

python:
  - "3.5"
  - "3.6"

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

install:
  - pip install -r requirements.txt

script:
  - pytest